/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  safelist: [
    'rotate-[-85deg]',
    'rotate-[-80deg]',
    'rotate-[-75deg]',
    'rotate-[-70deg]',
    'rotate-[-65deg]',
    'rotate-[-60deg]',
    'rotate-[-55deg]',
    'rotate-[-50deg]',
    'rotate-[-45deg]',
    'rotate-[-40deg]',
    'rotate-[-35deg]',
    'rotate-[-30deg]',
    'rotate-[-25deg]',
    'rotate-[-20deg]',
    'rotate-[-15deg]',
    'rotate-[-10deg]',
    'rotate-[-5deg]',
    'rotate-[0deg]',
    'rotate-[5deg]',
    'rotate-[10deg]',
    'rotate-[15deg]',
    'rotate-[20deg]',
    'rotate-[25deg]',
    'rotate-[30deg]',
    'rotate-[35deg]',
    'rotate-[40deg]',
    'rotate-[45deg]',
    'rotate-[50deg]',
    'rotate-[55deg]',
    'rotate-[60deg]',
    'rotate-[65deg]',
    'rotate-[70deg]',
    'rotate-[75deg]',
    'rotate-[80deg]',
    'rotate-[85deg]',
    'rotate-[90deg]',
  ],
  theme: {
    extend: {
    },
  },
  plugins: [],
};
